FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /
COPY HwInf.sln ./
COPY HwInf.Web/*.csproj ./HwInf.Web/
COPY HwInf.Common/*.csproj ./HwInf.Common/
COPY HwInf.BusinessLogic/*.csproj ./HwInf.BusinessLogic/
COPY HwInf.DataAccess/*.csproj ./HwInf.DataAccess/
COPY HwInf.Services/*.csproj ./HwInf.Services/
COPY HwInf.DinkToPdf/*.csproj ./HwInf.DinkToPdf/
COPY HwInf.UnitTests/*.csproj ./HwInf.UnitTests/

RUN dotnet restore
COPY . .
WORKDIR HwInf.Web
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HwInf.Web.dll"]