// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HwInf.Common
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using HwInf.Common.DAL;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class Contract : ContractBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write(@"
\document
[
    Info
    {
        Title = ""Ausleihvertrag""
        Subject = ""Technikum Wien Ausleihvertrag""
        Author = ""HW-INF.Technikum-Wien""
    }
]
{
	\section
	{


		\paragraph [ Format { Font { Size = 14 Bold = true }
                              SpaceBefore = ""1cm""
							  SpaceAfter = ""1cm""
							  LeftIndent = ""6.6cm""} ]
		{
			Leihvertrag
		}
		\paragraph 
		{
			Zwischen
		}
		\paragraph [ Format {LeftIndent = ""1cm""} ]
		{
			der Fachhochschule Technikum Wien,
		}
		\paragraph [ Format {LeftIndent = ""1cm""} ]
		{
			vertreten durch eine/n MitarbeiterIn des Instituts für Informatik
		}
		\paragraph [ Format {LeftIndent = ""1cm""} ]
		{
			Adresse: Höchstädtplatz 5, A-1200 Wien 
		}
		\paragraph [ Format { Font { Bold = true } LeftIndent = ""12cm""} ]
		{
			-VerleiherIn-
		}
		\paragraph 
		{
			und
		}
		
		");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getEntleiher()));
            
            #line default
            #line hidden
            this.Write(@"
		
		\paragraph [ Format { Font { Bold = true } LeftIndent = ""12cm""} ]
		{
			-EntleiherIn-
		}
		\paragraph
		{
			wird der folgende Leihvertrag geschlossen:
		}
		\paragraph [ Format { Font { Size = 7.5 Bold = true}
							  SpaceBefore = ""1cm""} ]
		{
		§ 1 Vertragsgegenstand
		}
		
		");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getGeraete()));
            
            #line default
            #line hidden
            this.Write("\n\t\t\\paragraph [ Format { Font { Size = 7.5} \n\t\t\t\t\t\t\tSpaceAfter = \"0.25cm\"} ]\n\t\t{\n" +
                    "\t\tDas Zubehör ist in der als Anlage zu diesem Vertrag beigefügten Bestandsliste " +
                    "aufgeführt. Die Bestandsliste ist Bestandteil dieses\nVertrages. Entleiherin oder" +
                    " Entleiher können nur Studierende der FH Technikum Wien sein. Ein Anspruch auf A" +
                    "bschluss oder Verlängerung\ndes Leihvertrages besteht nicht.\n\t\t}\n\t\t\\paragraph [ F" +
                    "ormat { Font { Size = 7.5}\n\t\t\t\t\t\t\t  SpaceAfter = \"1cm\"} ]\n\t\t{\n\t\t(2)    Die Leihe" +
                    " erfolgt im Rahmen der Ausbildung zur Unterstützung bei Projekten oder als befri" +
                    "stete Übergangslösung.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5 Bold = true" +
                    "} \n\t\t\t\t\t\t\t\tSpaceAfter = \"0.25cm\"} ]\n\t\t{\n\t\t§ 2 Vertragsgemäßer Gebrauch, Ausschlu" +
                    "ss von der Nutzung\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} SpaceAfter = \"" +
                    "1cm\"} ]\n\t\t{\n\t\t(1)    Das Gerät wird ausschließlich für Zwecke von Forschung, Leh" +
                    "re und Studium entliehen. Eine Nutzung für gewerbliche,\nerwerbswirtschaftliche, " +
                    "private oder sonstige Zwecke, die mit dem in § 1 Abs. 2 genannten Ausbildungszwe" +
                    "ck nicht vereinbar sind, ist\nuntersagt.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size " +
                    "= 7.5} SpaceAfter = \"0.25cm\"} ]\n\t\t{\n\t\t(2)    Eine Weitergabe bzw. Überlassung de" +
                    "s Gebrauchs des entliehenen Gerätes an Dritte ist untersagt. Technische Ressourc" +
                    "en des\nGerätes dürfen Dritten nicht zugänglich gemacht werden. Die auf dem Gerät" +
                    " installierten Programme und Software dürfen vom/von\nder EntleiherIn nicht kopie" +
                    "rt werden. Der/die EntleiherIn erhält ein vorinstalliertes System und muss das S" +
                    "ystem während der Leihzeit\nselbst administrieren. Es bestehen keine Ansprüche au" +
                    "f regelmäßige Wartung des Systems seitens der VerleiherIn. Eingriffe in die\nHard" +
                    "ware bzw. die Ausstattung des Gerätes durch den/die EntleiherIn sind nicht gesta" +
                    "ttet. Solange der/die EntleiherIn das Gerät\nausgeliehen hat, darf er/sie eigene " +
                    "legal erworbene Software installieren, soweit diese zur Erfüllung des Ausbildung" +
                    "szweckes\nerforderlich ist. Die VerleiherIn übernimmt für diesen Fall jedoch kein" +
                    "e Gewähr für die Nutzbarkeit des Geräts.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size" +
                    " = 7.5} SpaceAfter = \"1cm\"} ]\n\t\t{\n\t\t(3)    Die VerleiherIn kann den/die Entleihe" +
                    "rIn von der weiteren Nutzung des Gerätes ausschließen, wenn dieser/diese schuldh" +
                    "aft\nseinen/ihren Pflichten aus dieser Vereinbarung nicht nachkommt, das Gerät fü" +
                    "r strafbare Handlungen missbraucht oder der\nFachhochschule Technikum Wien durch " +
                    "sonstiges rechtswidriges Nutzerverhalten Nachteile entstehen.\n\t\t}\n\t\t\\paragraph [" +
                    " Format { Font { Size = 7.5 Bold = true} } ]\n\t\t{\n\t\t\t§ 3 Ausgabe und Rückgabe des" +
                    " Gerätes\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} SpaceAfter = \"0.25cm\" } " +
                    "]\n\t\t{\n\t\t\tDas Gerät nebst Zubehör wird von dem in dieser Vereinbarung genannten I" +
                    "nstitut ausgegeben. Bei diesem Institut ist das Gerät nebst\nZubehör auch wieder " +
                    "zurückzugeben.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5 Bold = true} } ]\n\t\t" +
                    "{\n\t\t\t§ 4 Mängel, Sorgfaltspflichten und Haftung\n\t\t}\n\t\t\\paragraph [ Format { Font" +
                    " { Size = 7.5} SpaceAfter = \"0.25cm\" } ]\n\t\t{\n\t\t(1) Der/die EntleiherIn hat sich " +
                    "bei der Übergabe von dem ordnungsgemäßen Zustand des Gerätes zu überzeugen und f" +
                    "estgestellte\nMängel und Schäden oder fehlendes Zubehör unverzüglich dem Fachbere" +
                    "ich anzuzeigen. Unterlässt der/die EntleiherIn die Anzeige,\nso gilt das Gerät al" +
                    "s in mangelfreiem Zustand und mit dem genannten Zubehör übergeben, es sei denn, " +
                    "dass es sich um einen\nMangel handelt, der bei der Untersuchung nicht erkennbar w" +
                    "ar. Zeigt sich später ein solcher Mangel, so muss die Anzeige\nunverzüglich schri" +
                    "ftlich an Herrn Benedikt Salzbrunn (salzbrunn@technikum-wien.at) bzw. dessen Ver" +
                    "tretung gemacht werden,\nanderenfalls ist der Einwand ausgeschlossen, ein mangelh" +
                    "aftes Gerät erhalten zu haben.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} Sp" +
                    "aceAfter = \"0.25cm\" } ]\n\t\t{\n\t\t(2) Der/die EntleiherIn verpflichtet sich zur sorg" +
                    "fältigen Behandlung des Gerätes und des Zubehörs sowie dieses vor Verlusten (auc" +
                    "h\nDiebstahl) und Beschädigungen zu schützen.\n\t\t}\n\t\t\\paragraph [ Format { Font { " +
                    "Size = 7.5} SpaceAfter = \"0.25cm\"} ]\n\t\t{\n\t\t(3) Der/die EntleiherIn hat Verluste " +
                    "sowie alle Mängel und Schäden des Gerätes, die während der Leihzeit auftreten, u" +
                    "nverzüglich dem\nausgebenden Fachbereich zu melden. Auf Verlangen ist ein schrift" +
                    "licher Schadensbericht vorzulegen. Der Diebstahl des Gerätes ist\ndarüber hinaus " +
                    "unverzüglich der Polizei anzuzeigen. Die Reparaturabwicklung bei aufgetretenen M" +
                    "ängeln und Schäden des Gerätes\nerfolgt ausschließlich über die IT-Abteilung des " +
                    "Technikum Wien. Der/die EntleiherIn darf Reparaturen weder selbst durchführen no" +
                    "ch\nin Auftrag geben.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} SpaceAfter =" +
                    " \"0.25cm\" } ]\n\t\t{\n\t\t(4) Der/die EntleiherIn haftet der VerleiherIn für die von i" +
                    "hm/ihr schuldhaft verursachten Schäden an der Leihgabe sowie für alle\nsonstigen " +
                    "Schäden, die dadurch entstehen, dass der/die EntleiherIn schuldhaft seinen/ihren" +
                    " Pflichten aus dieser Vereinbarung nicht\nnachkommt. Dem/der EntleiherIn obliegt " +
                    "der Beweis, dass ein schuldhaftes Verhalten nicht vorgelegen habe. Für Schäden a" +
                    "n der\nLeihgabe, die durch vertragswidrigen Gebrauch entstehen, haftet der/die En" +
                    "tleiherIn unabhängig vom Verschulden.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = " +
                    "7.5 Bold = true} SpaceAfter = \"0.5cm\"} ]\n\t\t{\n\t\t§ 6 Laufzeit und Ende des Vertrag" +
                    "es\n\t\t}\n\t\t\\paragraph [ Format { SpaceAfter = \"0.25cm\"}]\n\t\t{\n\t\t");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getZeitspanne()));
            
            #line default
            #line hidden
            this.Write("\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} SpaceAfter = \"0.25cm\" } ]\n\t\t{\n\t\tD" +
                    "er/die EntleiherIn ist verpflichtet, das Gerät während dieser Zeit der Verleiher" +
                    "In auf deren Verlangen jederzeit vorzuzeigen. Die\nVerleiherIn ist berechtigt, di" +
                    "e Leihe jederzeit zu kündigen.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5}} ]" +
                    "\n\t\t{\n\t\t(2) Der Vertrag endet jedenfalls unabhängig von dem in Absatz (1) genannt" +
                    "en Termin:\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5}} ]\n\t\t{\n\t\ta) wenn der/d" +
                    "ie EntleiherIn nicht mehr Studierende(r) der FH Technikum Wien ist,\n\t\t}\n\t\t\\parag" +
                    "raph [ Format { Font { Size = 7.5} SpaceAfter = \"0.25cm\"} ]\n\t\t{\n\t\tb) in den Fäll" +
                    "en des § 2 Absatz 3 dieses Leihvertrages.\n\t\t}\n\t\t\\paragraph [ Format { Font { Siz" +
                    "e = 7.5} SpaceAfter = \"0.25cm\"} ]\n\t\t{\n\t\t(3) Mit dem Ende des Vertrages ist das G" +
                    "erät nebst Zubehör unaufgefordert und unverzüglich zurückzugeben.\n\t\t}\n\t\t\\paragra" +
                    "ph [ Format { Font { Size = 7.5 Bold = true} SpaceAfter = \"0.5cm\"} ]\n\t\t{\n\t\t§ 7 N" +
                    "ebenbestimmungen\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} SpaceAfter = \"0." +
                    "25cm\"} ]\n\t\t{\n\t\t(1) Änderungen und Ergänzungen dieser Vereinbarung sowie Nebenabr" +
                    "eden bedürfen der Schriftform.\n\t\t}\n\t\t\\paragraph [ Format { Font { Size = 7.5} Sp" +
                    "aceAfter = \"0.25cm\"} ]\n\t\t{\n\t\t(2) Sollte eine Bestimmung dieses Vertrages unwirks" +
                    "am oder undurchführbar sein, beeinträchtigt dies nicht die Geltung der übrigen\nB" +
                    "estimmungen dieses Vertrages. Die Vertragsparteien werden sich in einem solchen " +
                    "Fall bemühen, die unwirksame oder\nundurchführbare Bestimmung durch eine andere z" +
                    "u ersetzen, die der zu ersetzenden Bestimmung möglichst nahe kommt.\n\t\t}\n\t\t\\parag" +
                    "raph [ Format { Font { Size = 7.5} SpaceAfter = \"0.5cm\"} ]\n\t\t{\n\t\t(3) Es gilt öst" +
                    "erreichisches Recht, Gerichtsstand ist das sachlich zuständige Gericht in Wien.\n" +
                    "\t\t}\n\t\t\\paragraph [ Format { SpaceAfter = \"1cm\"} ]\n\t\t{\n\t\tWien, den ");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
 this.Write(DateTime.Now.Day.ToString("d2"));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
 this.Write(DateTime.Now.Month.ToString("d2"));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
this.Write(DateTime.Now.Year.ToString()); 
            
            #line default
            #line hidden
            this.Write("\n\t\t}\n\t\t\\paragraph \n\t\t{ \n\t\t_____________________________                    ______" +
                    "_______________________\n\t\t}\n\t\t\\paragraph \n\t\t{\n\t\tUnterschrift VerleiherIn        " +
                    "                              Unterschrift EntleiherIn\n\t\t}\n\t}\n\t");
            
            #line 1 "C:\Users\Valentin\Documents\__FH\ITP3\git\HW-INF\HwInf.Common\Contract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getHandoff()));
            
            #line default
            #line hidden
            this.Write("\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ContractBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
